# Generated by Django 3.0.7 on 2020-06-30 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_unique_id'),
        ('account', '0002_auto_20200629_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'db_table': 'product_wishlists',
            },
        ),
        migrations.CreateModel(
            name='Look_wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Look')),
            ],
            options={
                'db_table': 'look_wishlists',
            },
        ),
    ]
