# Generated by Django 3.0.7 on 2020-06-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookimage',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
