# Generated by Django 3.0.7 on 2020-06-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('attributes', '0002_auto_20200627_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ManyToManyField(related_name='size', through='attributes.SizeProduct', to='products.Product'),
        ),
    ]
